import os
import json
import uuid
import re
import math
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

app = Flask(__name__)

# --- RATE LIMITER SETUP ---
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

groq_client = Groq()
LOG_FILE = "audit_log.json"

def read_audit_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, 'r') as f:
        try:
            return json.load(f)
        except json.JSONDecodeError:
            return []

def write_audit_log(entry):
    logs = read_audit_log()
    logs.append(entry)
    with open(LOG_FILE, 'w') as f:
        json.dump(logs, f, indent=2)

def signal_1_llm_semantic(text):
    """Signal 1: Groq LLM Semantic Analysis (0.0 = Human, 1.0 = AI)"""
    try:
        chat_completion = groq_client.chat.completions.create(
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a sophisticated AI detection system. Analyze the following text "
                        "and determine the probability that it was generated by an AI. "
                        "Return ONLY a single float value between 0.0 (definitely human) and 1.0 (definitely AI). "
                        "Do not output any other words, explanations, or formatting."
                    )
                },
                {
                    "role": "user",
                    "content": text,
                }
            ],
            model="llama-3.1-8b-instant",
            temperature=0.0
        )
        score_str = chat_completion.choices[0].message.content.strip()
        return float(score_str)
    except Exception as e:
        print(f"Error in Signal 1: {e}")
        return 0.50

def signal_2_stylometrics(text):
    """Signal 2: Sentence Length Variance (0.0 = Human, 1.0 = AI)"""
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if len(sentences) < 2:
        return 0.50
        
    word_counts = [len(s.split()) for s in sentences]
    mean_length = sum(word_counts) / len(word_counts)
    variance = sum((count - mean_length) ** 2 for count in word_counts) / len(word_counts)
    std_dev = math.sqrt(variance)
    
    score = 1.0 - (min(std_dev, 10.0) / 10.0)
    return round(score, 2)

# --- SUBMISSION ENDPOINT ---
@app.route('/submit', methods=['POST'])
@limiter.limit("5 per minute; 50 per day") # Defensible limit: A human writer doesn't need to submit >5 drafts a minute.
def submit_content():
    data = request.get_json()
    if not data or 'text' not in data or 'creator_id' not in data:
        return jsonify({"error": "Missing 'text' or 'creator_id' in request body"}), 400

    text = data['text']
    creator_id = data['creator_id']
    content_id = str(uuid.uuid4())
    timestamp = datetime.now(timezone.utc).isoformat()

    sig1_score = signal_1_llm_semantic(text)
    sig2_score = signal_2_stylometrics(text)

    # 70/30 Weighting Calibration
    final_confidence = round((sig1_score * 0.7) + (sig2_score * 0.3), 2)
    #final_confidence = round((sig1_score * 0.6) + (sig2_score * 0.4), 2)

    if final_confidence >= 0.65:
        attribution = "likely_ai"
        label = "High-Confidence AI: Our analysis strongly indicates this content was generated by artificial intelligence."
    elif final_confidence <= 0.40:
        attribution = "likely_human"
        label = "High-Confidence Human: Our analysis indicates a strong likelihood that this content was naturally authored by a human."
    else:
        attribution = "uncertain"
        label = "Uncertain Origin: Our system detected mixed signals. This content may be heavily edited human work, or AI-generated text modified to appear human."

    log_entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": timestamp,
        "attribution": attribution,
        "confidence": final_confidence,
        "signals": {
            "llm_semantic": sig1_score,
            "stylometrics": sig2_score
        },
        "status": "processed"
    }
    write_audit_log(log_entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": final_confidence,
        "label": label
    }), 201

# --- APPEALS ENDPOINT ---
@app.route('/appeal', methods=['POST'])
def appeal_content():
    data = request.get_json()
    if not data or 'content_id' not in data or 'creator_reasoning' not in data:
        return jsonify({"error": "Missing 'content_id' or 'creator_reasoning'"}), 400

    content_id = data['content_id']
    reasoning = data['creator_reasoning']
    
    logs = read_audit_log()
    
    # Find the specific log entry by content_id
    entry_to_update = next((item for item in logs if item.get("content_id") == content_id), None)
    
    if not entry_to_update:
        return jsonify({"error": "Submission not found"}), 404
        
    # Update the status and append the reasoning
    entry_to_update["status"] = "under_review"
    entry_to_update["appeal_reasoning"] = reasoning
    
    # Save the updated logs back to the JSON file
    with open(LOG_FILE, 'w') as f:
        json.dump(logs, f, indent=2)

    return jsonify({
        "message": "Appeal logged successfully.",
        "status": "under_review",
        "content_id": content_id
    }), 200

@app.route('/log', methods=['GET'])
def get_log():
    logs = read_audit_log()
    return jsonify({"entries": logs}), 200

if __name__ == '__main__':
    app.run(debug=True, port=5001)